// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvtvlwvnraifewcocecq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dHZsd3ZucmFpZmV3Y29jZWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTYzMDgsImV4cCI6MjA2ODM3MjMwOH0.QTQo0JYWPcM7oVQPHIj_m7wxxQcMqBbQoWSNKMePz_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});